HTTP/1.1 200 OK
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Cross-Origin-Resource-Policy: same-site
Vary: Origin
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 52
ETag: W/"34-SrfNg4laO3l3H5IU0FK/r2q/o+A"
Date: Sat, 07 Mar 2026 10:39:58 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"openTickets":6,"slaBreaches":2,"unpaidInvoices":1}